### PR TITLE
Update kured version


### PR DESCRIPTION
**Pull request by evrardjp**
We've updated kured for the next release, so we should bump the
version here.

### CODE REVIEW

**Comment by evrardjp** [comment]
Do not merge until a new image for kured is published, the PR https://github.com/SUSE/skuba/pull/972 is merged, and a new release of skuba to use this is issued.

**Comment by jordimassaguerpla** [comment]
Just to make sure, this is not in 4.1.2.

**Comment by evrardjp** [comment]
That seems for 4.2 indeed. Do you intend to change the versions in one go (no pun intended), or do you prefer doing it like this?

**Comment by r0ckarong** [comment]
This then also needs to be bumped in the doc repo (https://github.com/SUSE/doc-caasp/blob/master/adoc/attributes.adoc)

**Comment by evrardjp** [comment]
@r0ckarong I have added the doc change. It is tracked in the main card: https://github.com/SUSE/avant-garde/issues/1346

**Comment by r0ckarong** [comment]
> That seems for 4.2 indeed. Do you intend to change the versions in one go (no pun intended), or do you prefer doing it like this?

I think we need to do both. "Collect" updated versions along the development and then do a final check before the release. I would expect @jordimassaguerpla to do this final check as the packaging manager for the release. I try to remind him each time before release.

If we only do one check at the end there is a chance that we miss some component update.
Maybe we can start a PR for each release (like "prepare 4.2 release") and then add all kinds of commits to that, this makes it harder though to hold back something that can't be shipped.

I'm fine with doing separate PRs as long as we clearly understand which version this should be merged into.

/cc @jordimassaguerpla @evrardjp @nkoranova

**Comment by evrardjp** [comment]
I prefer pushing patches here, because if I don't, I am totally gonna forget things. As long as I can push _somewhere_ I am good. If that's a release process file, it's fine for me too.

**Comment by jordimassaguerpla** [comment]
In the release coordination planning we put this for 4.2.1.

**Comment by evrardjp** [comment]
@jordimassaguerpla can we go ahead?
@nkoranova is this okay for you?

**Comment by nkoranova** [comment]
Thanks for the PR @evrardjp, I don't think we are merging this until we actually have 4.2.1 on the table, right now it's still 4.1.2 :scream_cat:

**Comment by jordimassaguerpla** [comment]
> Thanks for the PR @evrardjp, I don't think we are merging this until we actually have 4.2.1 on the table, right now it's still 4.1.2 scream_cat

Exactly. Nothing to be done right now.

@evrardjp Your task is done. You can close your issue in your board and Nora will take it from here once we are doing 4.2.1. If anything she will contact you.
thanks

**Comment by jordimassaguerpla** [comment]
hi! Just an update from backlog grooming. This should be part of 4.2.0.

**Comment by jordimassaguerpla** [comment]
Merged in https://github.com/SUSE/caasp-release-notes/pull/47

**Pull request closed without merging**
