### PR TITLE
Update versions for beta 4 release

### PR DESCRIPTION
**Pull request by ereslibre**

### CODE REVIEW

**Review by nkoranova — APPROVED** [review]

**Comment by r0ckarong** [comment]
@ereslibre The `kubedoc` variable must be updated with the version number and not rewritten. We have various references in the docs that read `{kubedoc}/some/page` and point to the specific versioned page.

@nkoranova Can you please fix this.

Also the contents of `attributes.adoc` must also be updated in the main docs repo.

**Comment by nkoranova** [comment]
> @ereslibre The `kubedoc` variable must be updated with the version number and not rewritten. We have various references in the docs that read `{kubedoc}/some/page` and point to the specific versioned page.

@r0ckarong, Rafa and I were discussing this yesterday, the trouble is that the 1.15 docs don't seem to have a versioned path yet, it's just https://kubernetes.io/docs/home/ and it will probably only be created with 1.16. @ereslibre is asking upstream, if they can create it. 

> Also the contents of `attributes.adoc` must also be updated in the main docs repo.

https://github.com/SUSE/doc-caasp/pull/349

**Comment by ereslibre** [comment]
> @ereslibre The kubedoc variable must be updated with the version number and not rewritten. We have various references in the docs that read {kubedoc}/some/page and point to the specific versioned page.

It's not that easy at the moment. I was discussing this yesterday with @nkoranova. I think we could raise this with the Kubernetes doc team because I couldn't find a versioned Kubernetes documentation for the 1.15 release, it seems that if it's the latest release they redirect you to the unversioned host (https://kubernetes.io/docs/home/), and doesn't seem to be a versioned one like there is for older releases: https://v1-14.docs.kubernetes.io/docs/.

**Comment by r0ckarong** [comment]
I wasn't aware of this :/ Sorry. Then we'll go with the unversioned one as you already did.

**Pull request merged**
