### PR TITLE
Add developer documentation


### PR DESCRIPTION
**Pull request by evrardjp**
Instead of requiring developers to install software on their
systems, we could simply document what can be done based on the
existing Dockerfile behaviour.

### CODE REVIEW

**Comment by r0ckarong** [comment]
This README is a copy from the official doc-caasp repo and not specifically intended for CaaSP devs but anyone wanting to contribute. I doubt they will have all the necessary docker packages installed and configured to run what you suggest, right?

**Comment by evrardjp** [comment]
> This README is a copy from the official doc-caasp repo and not specifically intended for CaaSP devs but anyone wanting to contribute. I doubt they will have all the necessary docker packages installed and configured to run what you suggest, right?

Well I thought it's more likely they would have docker/podman than the rest. Myself I don't have all the necessary packages (daps), but I think it's easy with all of this published :)

**Comment by evrardjp** [comment]
Though I won't die if this doesn't merge. It will exercise my memory :)

**Comment by evrardjp** [comment]
After further thinking, I still think this should be in, but I am fine with this not merged.

**Comment by r0ckarong** [comment]
OK I will put this in, let's see if that helps.

**Pull request merged**
