### PR TITLE
add info about new vmware tf config

### PR DESCRIPTION
**Pull request by Itxaka**

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
@Itxaka could you make it against https://github.com/SUSE/caasp-release-notes/tree/release-5.0.0 instead?

**Comment by Itxaka** [comment]
> @Itxaka could you make it against release-5.0.0 instead?

mmmh, should it be master *then* backport to 5.0.0 branch??? @jordimassaguerpla 

Makes no sense to have it on a release branch and not on master...

**Comment by jordimassaguerpla** [comment]
> > @Itxaka could you make it against release-5.0.0 instead?
> 
> mmmh, should it be master _then_ backport to 5.0.0 branch??? @jordimassaguerpla
> 
> Makes no sense to have it on a release branch and not on master...

Let me ask Nora.
@nkoranova where should this PR be target to?

**Comment by nkoranova** [comment]
So `master` now has the preparations for 4.2.2. I've got the most recent changes for 5.0.0 in the `beta` branch. If you could make the PR against `beta`, that would be really helpful. Thanks.

**Pull request closed without merging**
